/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import modelo.LibroDAO;
import controlador.Validador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Libro;

/**
 *
 * @author Vania
 */
public class LibroVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibroVista.class.getName());

    /**
     * Creates new form LibroVista
     */
    Validador v = new Validador();
    Controlador c = new Controlador();
    
    public LibroVista() {
        initComponents();
        cargar();
    }

    public void cargar(){
        int idLibro, anio;
        String titulo, autor, categoria;
        boolean disponible;
        
        DefaultTableModel modelo = (DefaultTableModel)this.jTableLibro.getModel();
        modelo.setRowCount(0);
        ArrayList<Libro> lista = c.listlibro();
        
        for (Libro tmp : lista) {
            idLibro = tmp.getIdLibro();
            titulo = tmp.getTitulo();
            autor = tmp.getAutor();
            anio = tmp.getAnio();
            categoria = tmp.getCategoria();
            disponible = tmp.isDisponible();
            modelo.addRow(new Object[]{idLibro,titulo,autor,anio,categoria,disponible});
        }
        lista = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel9 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregarLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibro = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jTextFieldAnio = new javax.swing.JTextField();
        jTextFieldBorrarLibro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonBorrarLibro = new javax.swing.JButton();
        jButtonActualizarLibro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIdLibroActualizar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        getContentPane().setLayout(layout);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accion", "Terror", "Infantil", "Novela", "Comic", "Ciencia" }));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jComboBoxCategoria, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Gestion de Libros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel1, gridBagConstraints);

        jButtonAgregarLibro.setText("Agregar");
        jButtonAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarLibroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(jButtonAgregarLibro, gridBagConstraints);

        jTableLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdLibro", "Titulo", "Autor", "Año", "Categoria", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLibro);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 13;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel2.setText("Titulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Autor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Año");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Categoria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel5, gridBagConstraints);

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextFieldTitulo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextFieldAutor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextFieldAnio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextFieldBorrarLibro, gridBagConstraints);

        jLabel6.setText("ID Libro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel6, gridBagConstraints);

        jButtonBorrarLibro.setText("Borrar");
        jButtonBorrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarLibroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jButtonBorrarLibro, gridBagConstraints);

        jButtonActualizarLibro.setText("Actualizar");
        jButtonActualizarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarLibroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(jButtonActualizarLibro, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Agregar / Actualizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Eliminar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel10.setText("Id Libro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel10, gridBagConstraints);

        jTextFieldIdLibroActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdLibroActualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextFieldIdLibroActualizar, gridBagConstraints);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 14;
        getContentPane().add(jButtonBuscar, gridBagConstraints);

        jLabel11.setText("Titulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        getContentPane().add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextFieldBuscar, gridBagConstraints);

        jLabel12.setText("Buscar Libro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel12, gridBagConstraints);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        getContentPane().add(jButton1, gridBagConstraints);

        setBounds(0, 0, 897, 583);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jButtonAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarLibroActionPerformed
        int anio;
        String titulo, autor, categoria, valor;
        boolean disponible;
        
        valor = this.jTextFieldTitulo.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Titulo es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldTitulo.requestFocus();
            return ;
        }
        titulo = valor;
        
        valor = this.jTextFieldAutor.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Autor es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldAutor.requestFocus();
            return ;
        }
        autor = valor;
        
        valor = this.jTextFieldAnio.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Año del libro es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldAnio.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Año debe ser un entero.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldAutor.requestFocus();
            return ;
        }
        anio = Integer.parseInt(valor);
        
        categoria = (String) jComboBoxCategoria.getSelectedItem();
        
        disponible = true;
        
        Libro libro = new Libro(titulo, autor, anio, categoria, disponible);
        
        if(c.add(libro)){
            JOptionPane.showMessageDialog(this, "Libro agregado correctamente.", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
            this.jTextFieldAutor.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "Libro NO agregado.", "Error.", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldAutor.requestFocus();
        }
        cargar();
        
    }//GEN-LAST:event_jButtonAgregarLibroActionPerformed

    private void jButtonActualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarLibroActionPerformed
        int idLibro, anio;
        String titulo, autor, categoria, valor;
        
        valor = this.jTextFieldTitulo.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Titulo es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldTitulo.requestFocus();
            return ;
        }
        titulo = valor;
        
        valor = this.jTextFieldAutor.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Autor es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldAutor.requestFocus();
            return ;
        }
        autor = valor;
        
        valor = this.jTextFieldAnio.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Año del libro es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldAnio.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Año debe ser un entero.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldAnio.requestFocus();
            return ;
        }
        anio = Integer.parseInt(valor);
        
        categoria = (String) jComboBoxCategoria.getSelectedItem();
        
        valor = this.jTextFieldIdLibroActualizar.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Id del libro es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldIdLibroActualizar.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Id debe ser un entero.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldIdLibroActualizar.requestFocus();
            return ;
        }
        idLibro = Integer.parseInt(valor);
        
        Libro libro = new Libro(idLibro, titulo, autor, anio, categoria);
        
        if(c.act(libro)){
            JOptionPane.showMessageDialog(this, "Libro actualizado correctamente.", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Libro NO actualizado.", "Error.", JOptionPane.ERROR_MESSAGE);
        }
        cargar();
    }//GEN-LAST:event_jButtonActualizarLibroActionPerformed

    private void jButtonBorrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarLibroActionPerformed
        int idLibro;
        String valor;
        
        valor = this.jTextFieldBorrarLibro.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Id del libro es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldBorrarLibro.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Id debe ser un entero.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldBorrarLibro.requestFocus();
            return ;
        }
        idLibro = Integer.parseInt(valor);
        
        if(c.dellibro(idLibro)){
            JOptionPane.showMessageDialog(this, "Libro actualizado correctamente.", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Libro NO actualizado.", "Error.", JOptionPane.ERROR_MESSAGE);
        }
        cargar();
    }//GEN-LAST:event_jButtonBorrarLibroActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String titulo, valor;
        int idLibro, anio;
        String autor, categoria;
        boolean disponible;
        valor = this.jTextFieldBuscar.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Titulo es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldBuscar.requestFocus();
            return ;
        }
        titulo = valor;
        
        //DAO
        DefaultTableModel modelo = (DefaultTableModel)this.jTableLibro.getModel();
        modelo.setRowCount(0);
        ArrayList<Libro> lista = c.listlibro();
        
        for (Libro tmp : lista) {
            if(tmp.getTitulo().equalsIgnoreCase(titulo)){
                idLibro = tmp.getIdLibro();
                titulo = tmp.getTitulo();
                autor = tmp.getAutor();
                anio = tmp.getAnio();
                categoria = tmp.getCategoria();
                disponible = tmp.isDisponible();
                modelo.addRow(new Object[]{idLibro,titulo,autor,anio,categoria,disponible});
            }
        }
        lista = null;
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldIdLibroActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdLibroActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdLibroActualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c.vistaprincipal();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActualizarLibro;
    private javax.swing.JButton jButtonAgregarLibro;
    private javax.swing.JButton jButtonBorrarLibro;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLibro;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldBorrarLibro;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldIdLibroActualizar;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
