/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import controlador.Validador;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Libro;
import modelo.Prestamo;
import modelo.Usuario;

/**
 *
 * @author Vania
 */
public class PrestamoVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrestamoVista.class.getName());

    /**
     * Creates new form PrestamoVista
     */
    Validador v = new Validador();
    Controlador c = new Controlador();
    
    public PrestamoVista() {
        initComponents();
        cargar();
    }

    public void cargar(){
        int idUsuario, idPrestamo, idLibro;
        Date fechaPrestamo,fechaEstimada, fechaDevolucion;
        
        DefaultTableModel modelo = (DefaultTableModel)this.jTablePrestamos.getModel();
        modelo.setRowCount(0);
        ArrayList<Prestamo> lista = c.listprestamo();
        
        for (Prestamo tmp : lista) {
            idPrestamo = tmp.getIdPrestamo();
            idUsuario = tmp.getIdUsuario();
            idLibro = tmp.getIdLibro();
            fechaPrestamo = tmp.getFechaPrestamo();
            fechaEstimada = tmp.getFechaEstimada();
            fechaDevolucion = tmp.getFechaDevolucion();
            modelo.addRow(new Object[]{idPrestamo,idUsuario,idLibro, fechaPrestamo, fechaEstimada, fechaDevolucion});
        }
        lista = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrestamos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtLibroPrest = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        jButtonRegistrarPrest = new javax.swing.JButton();
        txtUsuarioPrest = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdPrestamoDevolucion = new javax.swing.JTextField();
        jButtonDevolucionLibro = new javax.swing.JButton();
        jButtonPendientes = new javax.swing.JButton();
        jBottonHistorial = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Gestion de Prestamos");

        jTablePrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPrestamo", "idUsuario", "idLibro", "fechaPrestamo", "fechaEstimada", "fechaDevolucion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePrestamos);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Libro Id:");

        jLabel2.setText("Registrar Prestamo");

        label12.setText("Usuario id:");

        jButtonRegistrarPrest.setText("Registrar");
        jButtonRegistrarPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPrestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRegistrarPrest)
                            .addComponent(txtLibroPrest, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtUsuarioPrest))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label12)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUsuarioPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtLibroPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrarPrest)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Devolucion de Libro");

        jLabel5.setText("id Prestamo:");

        jButtonDevolucionLibro.setText("Registrar Devolucion");
        jButtonDevolucionLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolucionLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPrestamoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButtonDevolucionLibro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdPrestamoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonDevolucionLibro)
                .addGap(21, 21, 21))
        );

        jButtonPendientes.setText("Pendientes");
        jButtonPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPendientesActionPerformed(evt);
            }
        });

        jBottonHistorial.setText("Historial");
        jBottonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBottonHistorialActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBottonHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBottonHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPrestActionPerformed
        int idu, idl;
        String valor;
        
        valor = this.txtUsuarioPrest.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Rut es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtUsuarioPrest.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Id del usuario debe ser entero", "Validacion", JOptionPane.WARNING_MESSAGE);
            this.txtLibroPrest.requestFocus();
        }
        idu = Integer.parseInt(valor);
        for (Usuario u : c.listusuario()) {
            if(idu == u.getIdUsuario()){
                idu = u.getIdUsuario();
                break;
            }
        }
        valor = this.txtLibroPrest.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Id del libro es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtLibroPrest.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Id del libro debe ser entero", "Validacion", JOptionPane.WARNING_MESSAGE);
            this.txtLibroPrest.requestFocus();
        }
        idl = Integer.parseInt(valor);
        for (Libro l : c.listlibro()) {
            if(idl == l.getIdLibro()){
                idl = l.getIdLibro();
                break;
            }
        }
        Date hoy = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(hoy);
        cal.add(Calendar.MONTH, 2);
        Date fechaEstimada = cal.getTime();
        
        Prestamo pres = new Prestamo(idu, idl, hoy, fechaEstimada,null);
        
        if(c.add(pres)){
            JOptionPane.showMessageDialog(this, "Prestamo registrado correctamente.", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Prestamo NO registrado.", "Error.", JOptionPane.ERROR_MESSAGE);
        }
        Libro libro = new Libro(false);
        c.nodisponible(libro);
        cargar();
    }//GEN-LAST:event_jButtonRegistrarPrestActionPerformed

    private void jButtonPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPendientesActionPerformed
        int idUsuario, idPrestamo, idLibro;
        Date fechaPrestamo,fechaEstimada, fechaDevolucion;
        
        DefaultTableModel modelo = (DefaultTableModel)this.jTablePrestamos.getModel();
        modelo.setRowCount(0);
        ArrayList<Prestamo> lista = c.pendientes();
        
        for (Prestamo tmp : lista) {
            idPrestamo = tmp.getIdPrestamo();
            idUsuario = tmp.getIdUsuario();
            idLibro = tmp.getIdLibro();
            fechaPrestamo = tmp.getFechaPrestamo();
            fechaEstimada = tmp.getFechaEstimada();
            fechaDevolucion = tmp.getFechaDevolucion();
            modelo.addRow(new Object[]{idPrestamo,idUsuario,idLibro, fechaPrestamo, fechaEstimada, fechaDevolucion});
        }
        lista = null;
    }//GEN-LAST:event_jButtonPendientesActionPerformed

    private void jBottonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBottonHistorialActionPerformed
        int idUsuario, idPrestamo, idLibro;
        Date fechaPrestamo,fechaEstimada, fechaDevolucion;
        
        DefaultTableModel modelo = (DefaultTableModel)this.jTablePrestamos.getModel();
        modelo.setRowCount(0);
        ArrayList<Prestamo> lista = c.historial();
        
        for (Prestamo tmp : lista) {
            idPrestamo = tmp.getIdPrestamo();
            idUsuario = tmp.getIdUsuario();
            idLibro = tmp.getIdLibro();
            fechaPrestamo = tmp.getFechaPrestamo();
            fechaEstimada = tmp.getFechaEstimada();
            fechaDevolucion = tmp.getFechaDevolucion();
            modelo.addRow(new Object[]{idPrestamo,idUsuario,idLibro, fechaPrestamo, fechaEstimada, fechaDevolucion});
        }
        lista = null;
    }//GEN-LAST:event_jBottonHistorialActionPerformed

    private void jButtonDevolucionLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolucionLibroActionPerformed
        int idPrestamo, idUsuario = 0, idLibro = 0;
        Date fechaPrestamo = null, fechaEstimada = null, fechaDevolucion = null;
        String valor;
        
        
        valor = this.txtIdPrestamoDevolucion.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Id del usuario es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtIdPrestamoDevolucion.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Id debe ser un entero.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtIdPrestamoDevolucion.requestFocus();
            return ;
        }
        idPrestamo = Integer.parseInt(valor);
        
        for (Prestamo p : c.listprestamo()) {
            if(idPrestamo == p.getIdPrestamo()){
                idPrestamo = p.getIdPrestamo();
                idUsuario = p.getIdUsuario();
                idLibro = p.getIdLibro();
                fechaPrestamo = p.getFechaPrestamo();
                fechaEstimada = p.getFechaEstimada();
                break;
            }
        }
        Date hoy = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(hoy);
        Prestamo prestamo = new Prestamo(idPrestamo, idUsuario, idLibro, fechaPrestamo, fechaEstimada, hoy);
        
        if(c.act(prestamo)){
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario NO actualizado.", "Error.", JOptionPane.ERROR_MESSAGE);
        }
        Libro libro = new Libro(true);
        c.sidisponible(libro);
        cargar();
        
    }//GEN-LAST:event_jButtonDevolucionLibroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c.vistaprincipal();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBottonHistorial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDevolucionLibro;
    private javax.swing.JButton jButtonPendientes;
    private javax.swing.JButton jButtonRegistrarPrest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrestamos;
    private javax.swing.JLabel label12;
    private javax.swing.JTextField txtIdPrestamoDevolucion;
    private javax.swing.JTextField txtLibroPrest;
    private javax.swing.JTextField txtUsuarioPrest;
    // End of variables declaration//GEN-END:variables
}
