/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import controlador.Validador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Libro;
import modelo.Usuario;


/**
 *
 * @author Vania
 */
public class UsuarioVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsuarioVista.class.getName());

    /**
     * Creates new form UsuarioVista
     */
    Validador v = new Validador();
    Controlador c = new Controlador();
    
    public UsuarioVista() {
        initComponents();
        cargar();
    }
    public void cargar(){
        int idUsuario, telefono;
        String nombre,apellido , rut;
        
        DefaultTableModel modelo = (DefaultTableModel)this.jTableUsuario.getModel();
        modelo.setRowCount(0);
        ArrayList<Usuario> lista = c.listusuario();
        
        for (Usuario tmp : lista) {
            idUsuario = tmp.getIdUsuario();
            nombre = tmp.getNombre();
            apellido = tmp.getApellido();
            rut = tmp.getRut();
            telefono = tmp.getTelefono();
            modelo.addRow(new Object[]{idUsuario,nombre,apellido,rut,telefono});
        }
        lista = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdUsuarioEliminar = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonBuscarRut = new javax.swing.JButton();
        txtNombreBuscar = new javax.swing.JTextField();
        txtBuscarRut = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonActualizar = new javax.swing.JButton();
        txtIdUsuarioActualizar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonBuscarNombre = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        getContentPane().setLayout(layout);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Gestion Usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel1, gridBagConstraints);

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idUsuario", "nombre", "apellido", "rut", "telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 21;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel2.setText("Registrar Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Rut");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtApellido, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtRut, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtTelefono, gridBagConstraints);

        jButtonAgregar.setText("Registrar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        getContentPane().add(jButtonAgregar, gridBagConstraints);

        jLabel6.setText("Telefono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setText("idUsuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("Borrar Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtIdUsuarioEliminar, gridBagConstraints);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        getContentPane().add(jButtonEliminar, gridBagConstraints);

        jLabel9.setText("Buscar Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel9, gridBagConstraints);

        jButtonBuscarRut.setText("Buscar Rut");
        jButtonBuscarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarRutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(jButtonBuscarRut, gridBagConstraints);

        txtNombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtNombreBuscar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtBuscarRut, gridBagConstraints);

        jLabel10.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel10, gridBagConstraints);

        jLabel11.setText("RUT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel11, gridBagConstraints);

        jLabel12.setText("Actualizar Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel12, gridBagConstraints);

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        getContentPane().add(jButtonActualizar, gridBagConstraints);

        txtIdUsuarioActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(txtIdUsuarioActualizar, gridBagConstraints);

        jLabel13.setText("Id Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        getContentPane().add(jLabel13, gridBagConstraints);

        jButtonBuscarNombre.setText("Buscar Nombre");
        jButtonBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        getContentPane().add(jButtonBuscarNombre, gridBagConstraints);

        jToggleButton1.setText("Volver");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 24;
        getContentPane().add(jToggleButton1, gridBagConstraints);

        setBounds(0, 0, 917, 573);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdUsuarioActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActualizarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        int telefono;
        String nombre, apellido, rut, valor;
        
        valor = this.txtNombre.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Titulo es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtNombre.requestFocus();
            return ;
        }
        nombre = valor;
        
        valor = this.txtApellido.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Autor es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtApellido.requestFocus();
            return ;
        }
        apellido = valor;
        
        valor = this.txtRut.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Año del libro es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtRut.requestFocus();
            return ;
        }
        
        rut = valor;
        
        valor = this.txtTelefono.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Año del libro es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtTelefono.requestFocus();
            return ;
        }
        telefono = Integer.parseInt(valor);
        
        Usuario user = new Usuario(nombre, apellido, rut, telefono);
        
        if(c.add(user)){
            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Usuraio NO registrado.", "Error.", JOptionPane.ERROR_MESSAGE);
        }
        cargar();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        int idUsuario, telefono;
        String nombre,apellido, rut, valor;
        
        valor = this.txtNombre.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Nombre es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtNombre.requestFocus();
            return ;
        }
        nombre = valor;
        
        valor = this.txtApellido.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Apellido es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtApellido.requestFocus();
            return ;
        }
        apellido = valor;
        
        valor = this.txtRut.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Rut del usuario es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtRut.requestFocus();
            return ;
        }
        
        rut = valor;

        
        valor = this.txtTelefono.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Id del usuario es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtTelefono.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Id debe ser un entero.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtTelefono.requestFocus();
            return ;
        }
        telefono = Integer.parseInt(valor);
        
        valor = this.txtIdUsuarioActualizar.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Id del usuario es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtIdUsuarioActualizar.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Id debe ser un entero.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtIdUsuarioActualizar.requestFocus();
            return ;
        }
        idUsuario = Integer.parseInt(valor);
        
        
        Usuario usuario = new Usuario(idUsuario, nombre, apellido, rut, telefono);
        
        if(c.act(usuario)){
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario NO actualizado.", "Error.", JOptionPane.ERROR_MESSAGE);
        }
        cargar();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int idUsuario;
        String valor;
        
        valor = this.txtIdUsuarioEliminar.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Id del usuario es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtIdUsuarioEliminar.requestFocus();
            return ;
        }
        if(!v.validaInt(valor)){
            JOptionPane.showMessageDialog(this, "Id debe ser un entero.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtIdUsuarioEliminar.requestFocus();
            return ;
        }
        idUsuario = Integer.parseInt(valor);
        
        if(c.delusuario(idUsuario)){
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.", "Informacion.", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario NO actualizado.", "Error.", JOptionPane.ERROR_MESSAGE);
        }
        cargar();
        //TODO verificacion de prestamo
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonBuscarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarRutActionPerformed
        String nombre, valor;
        int idUsuario, telefono;
        String rut, apellido;
        
        valor = this.txtBuscarRut.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Rut es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtBuscarRut.requestFocus();
            return ;
        }
        rut = valor;
        
        DefaultTableModel modelo = (DefaultTableModel)this.jTableUsuario.getModel();
        modelo.setRowCount(0);
        ArrayList<Usuario> lista = c.listusuario();
        
        for (Usuario tmp : lista) {
            if(tmp.getRut().equalsIgnoreCase(rut)){
                idUsuario = tmp.getIdUsuario();
                nombre = tmp.getNombre();
                apellido = tmp.getApellido();
                rut = tmp.getRut();
                telefono = tmp.getTelefono();
                modelo.addRow(new Object[]{idUsuario,nombre,apellido,rut,telefono});
            }
        }
        lista = null;
                 
    }//GEN-LAST:event_jButtonBuscarRutActionPerformed

    private void txtNombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarActionPerformed

    private void jButtonBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarNombreActionPerformed
        String nombre, valor;
        int idUsuario, telefono;
        String rut, apellido;
        
        valor = this.txtNombreBuscar.getText();
        if(!v.validaVacio(valor)){
            JOptionPane.showMessageDialog(this, "Nombre es obligatorio.", "Validacion.", JOptionPane.WARNING_MESSAGE);
            this.txtNombreBuscar.requestFocus();
            return ;
        }
        nombre = valor;
        
        DefaultTableModel modelo = (DefaultTableModel)this.jTableUsuario.getModel();
        modelo.setRowCount(0);
        ArrayList<Usuario> lista = c.listusuario();
        
        for (Usuario tmp : lista) {
            if(tmp.getRut().equalsIgnoreCase(nombre)){
                idUsuario = tmp.getIdUsuario();
                nombre = tmp.getNombre();
                apellido = tmp.getApellido();
                rut = tmp.getRut();
                telefono = tmp.getTelefono();
                modelo.addRow(new Object[]{idUsuario,nombre,apellido,rut,telefono});
            }
        }
        lista = null;
                       
    }//GEN-LAST:event_jButtonBuscarNombreActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        c.vistaprincipal();
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscarNombre;
    private javax.swing.JButton jButtonBuscarRut;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscarRut;
    private javax.swing.JTextField txtIdUsuarioActualizar;
    private javax.swing.JTextField txtIdUsuarioEliminar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
